# <center><font size="8">Prototipo de Oferta Dinámica Personalizada</font></center>

<div align="left"><font size="5">📌 Introducción</font></div>

## 1. Contexto y Objetivos

El presente proyecto se enfoca en el desarrollo de un sistema avanzado de **Oferta Dinámica (Dynamic Pricing)** con el objetivo primordial de **optimizar los ingresos y la rentabilidad** a través de la **personalización de tarifas**.  

En lugar de utilizar modelos de precio estáticos o ajustes basados únicamente en la demanda global, nuestro prototipo se cimenta en el **análisis individual del consumidor** para determinar el precio óptimo en tiempo real.  

Para lograr esta personalización, hemos diseñado un **pipeline de Machine Learning** que combina técnicas de **econometría**, **aprendizaje no supervisado** y **modelos predictivos**.

---

## 2. Metodología y Arquitectura del Modelo

La propuesta metodológica se basa en **tres fases interconectadas**, que transforman la sensibilidad del cliente en una tarifa personalizada:

---

### A. Estimación y Segmentación por Elasticidad (Fundamento Económico)

El primer pilar del prototipo fue la **estimación rigurosa de la elasticidad precio de la demanda ($\text{EPD}$)**.  
Esta métrica ha sido fundamental para entender el grado de respuesta de la cantidad demandada ante variaciones de precio en nuestros datos históricos.

Posteriormente, aplicamos un **algoritmo de clustering** (*aprendizaje no supervisado*) para **clasificar a los clientes** basándonos en su $\text{EPD}$ y otras características de comportamiento.  

Este *clustering* nos permitió crear **segmentos de clientes bien definidos** (por ejemplo: *“Extremadamente Elásticos”*, *“Inelásticos”*), estableciendo un **rango de ajuste de precios** (aumento o decremento) específico para cada grupo.

---

### B. Clasificación de Clientes Nuevos (Motor de XGBoost)

Una vez establecidos los segmentos de elasticidad, desarrollamos un **clasificador basado en el algoritmo XGBoost (eXtreme Gradient Boosting)**.  

La función de este modelo es crucial en la operativa:  
al recibir los datos de un nuevo cliente o una nueva interacción, **XGBoost predice a cuál de las categorías de elasticidad pre-clasificadas pertenece**.  

Esta predicción es el **factor determinante inicial** para estimar la tarifa personalizada, permitiéndonos saber si el sistema debe apuntar a un **aumento**, un **decremento** o un **precio base**.

---

### C. Determinación de la Oferta Dinámica (Red Neuronal)

Finalmente, para la etapa de determinación del precio, implementamos una **red neuronal artificial**.  

Este modelo de aprendizaje profundo **integra las características de la demanda**, la **clasificación de elasticidad obtenida de XGBoost**, y otras **variables dinámicas** (como inventario, hora del día y actividad de la competencia) para **estimar la oferta dinámica final y personalizada**.  

La red neuronal provee la **flexibilidad** y la **capacidad de capturar relaciones no lineales** necesarias para el ajuste preciso del precio a nivel individual.

<div align="left"><font size="5">📌 Objetivos</font></div>

- **1. Estimar la Elasticidad de la Demanda**  
  - Cuantificar la sensibilidad al precio ($\text{EPD}$) de los diferentes segmentos de clientes.  
  - Servirá como fundamento económico para la toma de decisiones de precio.

- **2. Segmentar Clientes por Comportamiento de Precio**  
  - Aplicar técnicas de *clustering para agrupar clientes en categorías de elasticidad homogéneas.  
  - Crear segmentos accionables que definan la estrategia inicial de aumento o decremento de precios.

- **3. Desarrollar un Motor de Clasificación de Clientes**  
  - Implementar y validar el algoritmo XGBoost para clasificar con alta precisión a nuevos clientes.  
  - Integrar la clasificación dentro de los segmentos de elasticidad previamente definidos.

- **4. Integrar un Pipeline Predictivo Completo**  
  - Crear un prototipo pipeline robusto que combine:  
    - **Clustering** (aprendizaje no supervisado)  
    - **Clasificación** (XGBoost)  
    - **Predicción** (Red Neuronal)  
- **5. Generar la tarifa final personalizada con tarifa dinámica**.

# <div align="left"><font size="5">📌 Librerias</font></div>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

from Tools import Tools4DataExtraction as T4DE
from Tools.Tools4Cluster import ClusteringData
from Tools.Tools4ClasSupervisada import ClusteringSupervisado
from Tools import Tools4TarifPer as T4TP
from Tools import Tools4Net as T4N 
from Tools import Tools4Elasticity as T4E
from Tools import Tools4CaracDemanda as TCD

# <div align="left"><font size="5">📌Extracción de información del modelo de datos</font></div>

In [2]:
# Se extraen los datos del modelo de datos
D4NN, D4C, D4C1, D4GC= T4DE.Get_Data()

Memoria usada antes: 630.76 MB
Memoria usada después: 122.53 MB
Reducción: 80.6%

In [3]:
TCD.BuenasCaracteristicas(D4GC)

# <div align="left"><font size="5">📌Calculo de la elasticidad</font></div>

La Elasticidad Precio de la Demanda (EPD) mide cómo la cantidad demandada de un producto cambia en respuesta a una variación en su precio. Se calcula como 

$$\epsilon_{Q} = \frac{\Delta Q}{\Delta P}$$

### Clasificación de la Elasticidad de la Demanda según su valor

**Demanda Elástica** ($|EPD| > 1$):  
La cantidad demandada varía en una proporción mayor que el cambio en el precio.  
Un pequeño cambio en el precio provoca un cambio significativo en la cantidad demandada.  
*Ejemplo:* Bienes de lujo o productos con muchos sustitutos disponibles.

---

**Demanda Inelástica** ($|EPD| < 1$):  
La cantidad demandada varía en una proporción menor que el cambio en el precio.  
Un cambio en el precio tiene poco impacto en la cantidad demandada.  
*Ejemplo:* Bienes de primera necesidad o esenciales, como medicamentos o gasolina (a corto plazo).

---

**Elasticidad Unitaria** ($|EPD| = 1$):  
La cantidad demandada varía en la misma proporción que el cambio en el precio.

In [4]:
T4E.MainElas()

Memoria usada antes: 630.76 MB
Memoria usada después: 122.53 MB
Reducción: 80.6%
La elasticidad de la demanda es: 0.7832

# <div align="left"><font size="5">📌Clasificación no supervisada</font></div>

La clasificación de clientes permite entender cómo distintos grupos responden al precio y al servicio, habilitando estrategias de precio personalizado que maximizan ingresos y reducen pérdida de demanda. Se calcula el **precio óptimo** según la respuesta esperada del segmento (elasticidad estimada o probabilidad de compra).

### 🔹 Estrategias diferenciadas
- **Segmento elástico →** precios competitivos o descuentos.  
- **Segmento inelástico →** precios premium o aumentos graduales.  
- **Segmento leal →** estabilidad de precios.

---

## 📊 Beneficios Clave

- 💰 **Maximiza los ingresos** ajustando precios según la disposición a pagar.  
- 📉 **Reduce pérdida de demanda** por aumentos injustificados.  
- 🎯 **Mejora la precisión del modelo**, al trabajar con segmentos más homogéneos.  
- 🧠 **Permite estrategias personalizadas y accionables** según el tipo de cliente.

In [5]:
# 0 es para todos los dias antes de ayer
# -1 es para todos los dias antes de 7 dias desde ayer
# 1 es desde ayer hasta hace un año
# 2 es para todos los dias antes de 20 dias desde ayer
Zero= 1
ClusteringData(False,D4C,Zero)

Modelo K-Means guardado exitosamente como: KmeansAllData.joblib

### Estrategia de Precios por *Cluster*

### Ajuste de Precio por Cluster

| Cluster | Estrategia                 | Descripción                                                           |
|:--------:|:--------------------------:|:----------------------------------------------------------------------|
| **3** | **+10% Sobrecosto**        | Clientes urgentes, pagan caro sin promo. Aprovechar elasticidad baja. |
| **1** | **+7.5% Sobrecosto**         | Clientes leales y poco sensibles, mantener precios altos.             |
| **4** | **+5% Ligero sobrecosto**  | Compradores mixtos, ajustar marginalmente.                            |
| **2** | **0% Descuento leve**     | Fieles pero algo sensibles, descuento simbólico.                      |
| **0** | **-2.5% Descuento moderado** | Alta anticipación y uso de promo, sensibles.                          |
| **5** | **-5% Descuento fuerte**   | Segmento más sensible, atraer con precios agresivos.                  |

# <div align="left"><font size="5">📌Extracción de la base de datos de los clusters generados</font></div>

In [6]:
# se extrae la base de datos de los clusters generados
DBClus= T4DE.GetDB()

# <div align="left"><font size="5">📌Clasificación supervisada</font></div>


La implementación de un algoritmo de aprendizaje supervisado es fundamental para transformar una base de datos de clientes clasificados en un sistema de tarifa dinámica eficiente y rentable.

El valor agregado reside en pasar de la segmentación estática a la predicción continua. 

| Componente | Rol en el Modelo de Tarifa Dinámica | Beneficio Clave |
| :--- | :--- | :--- |
| **Clasificación Inicial de Clientes** | Sirve como *input* (una de las características) para el modelo de Machine Learning. | Proporciona una base de datos histórica y segmentada de alta calidad. |
| **Algoritmo de Aprendizaje Supervisado** | Entrena un modelo para predecir el comportamiento del cliente y calcular el precio óptimo basándose en datos históricos etiquetados (transacciones y resultados). | Maximiza el ingreso al ajustar la tarifa en tiempo real a la disposición a pagar individual. |
| **Red neuronal (Output)** | Permite al modelo predecir un valor continuo y exacto (el precio de venta) en lugar de limitarse a asignar categorías predefinidas. | Permite un ajuste fino y automatizado de precios, respondiendo a la demanda, inventario, precios de la competencia y el perfil específico del cliente simultáneamente. |

In [7]:
# Se aplica la clasificación supervisada a la base de datos de los clusters generados
ClusteringSupervisado(DBClus)

Modelo XGBoost guardado exitosamente como: modelo_xgboost_clientes.json

# <div align="left"><font size="5">📌Calculando la tarifa dinámica</font></div>

Una red neuronal artificial (RNA) es una herramienta poderosa para pronosticar la tarifa dinámica porque sobresale en el manejo de la complejidad y las relaciones no lineales inherentes a la fijación de precios en el mercado.

Su principal utilidad es su capacidad para modelar la elasticidad de la demanda de forma muy precisa, considerando simultáneamente una gran cantidad de variables.

In [8]:
# 0 es para todos los dias antes de ayer
# -1 es para todos los dias antes de 7 dias desde ayer
# 1 es desde ayer hasta hace un año
T4N.ProcessingNet(D4NN,Zero)

# para pronosticar con todo el dataframe

# 0 es para el dia de hoy
# 1 es para hace 7 dias hasta hoy
# 2 es para hace 19 dias hasta hoy
bandera= 2
df_= T4N.PrepareData4Fore(D4NN,bandera)

#Fore= T4N.GetTodayData4Net(df_)
#PrecioDin=T4N.NewClientsPredNet(Fore)
#df_['PRECIO DINAMICO']=PrecioDin
#TodayDataPD= df_.copy()

# para pronosticar por cliente el dataframe
lista_resultados = []

for row in range(len(df_)):
    InfoClient = pd.DataFrame(df_.iloc[row]).T
    Foree= T4N.GetTodayData4Net(InfoClient)
    InfoClient["TARIFA DINAMICA"] = T4N.NewClientsPredNet(Foree)[0,0]
    
    lista_resultados.append(InfoClient)

TodayDataPD = pd.concat(lista_resultados, ignore_index=True)

El Error Absoluto Medio (MAE) final es de: 0.34 [Moneda]

La Raíz del Error Cuadrático Medio (RMSE) final es de: 0.52 [Moneda]
WARNING:tensorflow:5 out of the last 538 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000025ECAE9E7A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 539 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000025EC0B41B20> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [9]:
df_

,NOMBRE_PASAJERO,BOLETOS_VEND,FECHA_CORRIDA,HORA_SALIDA_CORRIDA,CLASE_SERVICIO,IVA_TARIFA_BASE_TRAMO,PAX_SUBEN,TARIFA_BASE_TRAMO,FECHA_OPERACION,HORA_OPERACION,VENTA,DISPONIBILIDAD_TRAMO,HORAS_ANTICIPACION,ORIGEN,DESTINO,TIPO_CLIENTE,NUM_ASIENTO,CAPACIDAD_ASIENTOS_TRAMO,TIPO_PASAJERO
393722,PEDRO CHAVEZ SANDOVAL,1.0,2025-10-24,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24,1900-01-01 00:32:16,1163.790039,2,2.0,MEXN,GDLJ,TAQUILLA,10,36,NI
393723,ALICIA ROLDAN GARCIA,1.0,2025-10-24,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24,1900-01-01 01:17:23,1163.790039,2,1.0,MEXN,GDLJ,TAQUILLA,8,36,NI
393724,GLORIA MIRANDA DURAN,1.0,2025-10-24,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24,1900-01-01 01:17:23,1163.790039,2,1.0,MEXN,GDLJ,TAQUILLA,9,36,NI
393725,MARCELO MIRANDA,1.0,2025-10-24,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24,1900-01-01 01:17:23,1163.790039,2,1.0,MEXN,GDLJ,TAQUILLA,11,36,AD
393726,IGNACIO MIRANDA,1.0,2025-10-24,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24,1900-01-01 01:17:23,1163.790039,2,1.0,MEXN,GDLJ,TAQUILLA,12,36,AD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396511,RAMON REBOLLEDO,1.0,2025-11-12,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12,1900-01-01 10:11:31,1163.790039,20,1.0,MEXN,GDLJ,TAQUILLA,36,36,AD
396512,PAULINA LLAMAS CASILLAS,1.0,2025-11-12,1900-01-01 23:59:00,DOS PISOS ETN,186.206406,9,1163.790039,2025-11-12,1900-01-01 10:16:35,1163.790039,27,13.0,MEXN,GDLJ,INTERNET,13,36,AD
396513,ARTURO CHAVEZ,1.0,2025-11-12,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12,1900-01-01 10:45:16,1163.790039,20,1.0,MEXN,GDLJ,TAQUILLA,30,36,AD
396514,MOISES PENHOS,1.0,2025-11-12,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12,1900-01-01 10:47:24,1163.790039,20,1.0,MEXN,GDLJ,TAQUILLA,24,36,AD
396515,ADRIANA ARMENTA RAMIREZ,1.0,2025-11-12,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12,1900-01-01 10:48:10,1163.790039,20,1.0,MEXN,GDLJ,TAQUILLA,18,36,IN

In [10]:
TodayDataPD

,NOMBRE_PASAJERO,BOLETOS_VEND,FECHA_CORRIDA,HORA_SALIDA_CORRIDA,CLASE_SERVICIO,IVA_TARIFA_BASE_TRAMO,PAX_SUBEN,TARIFA_BASE_TRAMO,FECHA_OPERACION,HORA_OPERACION,VENTA,DISPONIBILIDAD_TRAMO,HORAS_ANTICIPACION,ORIGEN,DESTINO,TIPO_CLIENTE,NUM_ASIENTO,CAPACIDAD_ASIENTOS_TRAMO,TIPO_PASAJERO,TARIFA DINAMICA
0,PEDRO CHAVEZ SANDOVAL,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 00:32:16,1163.790039,2,2.0,MEXN,GDLJ,TAQUILLA,10,36,NI,1081.420166
1,ALICIA ROLDAN GARCIA,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 01:17:23,1163.790039,2,1.0,MEXN,GDLJ,TAQUILLA,8,36,NI,1081.455322
2,GLORIA MIRANDA DURAN,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 01:17:23,1163.790039,2,1.0,MEXN,GDLJ,TAQUILLA,9,36,NI,1081.437378
3,MARCELO MIRANDA,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 01:17:23,1163.790039,2,1.0,MEXN,GDLJ,TAQUILLA,11,36,AD,1081.401489
4,IGNACIO MIRANDA,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 01:17:23,1163.790039,2,1.0,MEXN,GDLJ,TAQUILLA,12,36,AD,1081.383423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,RAMON REBOLLEDO,1.0,2025-11-12 00:00:00,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12 00:00:00,1900-01-01 10:11:31,1163.790039,20,1.0,MEXN,GDLJ,TAQUILLA,36,36,AD,1080.785278
2306,PAULINA LLAMAS CASILLAS,1.0,2025-11-12 00:00:00,1900-01-01 23:59:00,DOS PISOS ETN,186.206406,9,1163.790039,2025-11-12 00:00:00,1900-01-01 10:16:35,1163.790039,27,13.0,MEXN,GDLJ,INTERNET,13,36,AD,1081.106201
2307,ARTURO CHAVEZ,1.0,2025-11-12 00:00:00,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12 00:00:00,1900-01-01 10:45:16,1163.790039,20,1.0,MEXN,GDLJ,TAQUILLA,30,36,AD,1080.893188
2308,MOISES PENHOS,1.0,2025-11-12 00:00:00,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12 00:00:00,1900-01-01 10:47:24,1163.790039,20,1.0,MEXN,GDLJ,TAQUILLA,24,36,AD,1081.001343
2309,ADRIANA ARMENTA RAMIREZ,1.0,2025-11-12 00:00:00,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12 00:00:00,1900-01-01 10:48:10,1163.790039,20,1.0,MEXN,GDLJ,TAQUILLA,18,36,IN,1081.230835

# <div align="left"><font size="5">📌Obteniendo la elasticidad calculada</font></div>

La elasticidad calculada se guarda en un modelo de datos para posteriormente cargarla y hacer los cálculos necesarios en la segmentación de los clientes.

In [11]:
DataElas= T4E.GetDataElasticity()
Elas=DataElas['Elasticidad']

# <div align="left"><font size="5">📌Obteniendo datos del presente día para la tarifa personalizada</font></div>

Se cargan los datos del día presente del modelo de datos

In [12]:
# Se obtienen los datos de los clientes para obtener la tarifa personalizada
# 0 es para el dia de hoy
# 1 es para hace 7 dias hasta hoy
# 2 es para hace 19 dias hasta hoy
TodayData4C= T4TP.GetTodayData4Cluster(D4C1,bandera)

# <div align="left"><font size="5">📌Calculando el porcentaje de aumento para la tarifa personalizada</font></div>

Ya teniendo entrenados los algoritmos que clasificaron la data histórica de clientes, de manera supervisada y no supervisada, se procede a realizar una prueba de calidad con los datos del día corriente para poder observar el comportamiento de los precios personalizados.

In [13]:
# se simula la obtencion del cluster del cliente que está comprando
# para ver que tarifa personalizada se le asigna

import pandas as pd

# 1. Inicializa una lista vacía para guardar los resultados
lista_resultados = []

# 2. Itera y agrega cada DataFrame a la lista
for row in range(len(TodayData4C)):
    # 1. Crea la fila (DataFrame de 1xN)
    InfoClient = pd.DataFrame(TodayData4C.iloc[row]).T
    
    # 2. Procesa la información (asumo que T4TP.GetCluster devuelve Cluster y desc)
    Cluster, desc = T4TP.GetCluster(InfoClient, DBClus,Elas)
    
    # 3. Agrega la nueva columna
    InfoClient["%_Tarifa Personalizada"] = desc
    InfoClient["Cluster"] = Cluster
    InfoClient["Delta_Q"] = desc*Elas
    
    # 4. Agrega el DataFrame resultante a la lista
    lista_resultados.append(InfoClient)

# 3. Concatena todos los DataFrames de la lista de una sola vez
TodayDataTP = pd.concat(lista_resultados, ignore_index=True)

# El DataFrame 'final' ahora contiene todas las filas concatenadas

In [14]:
TodayDataTP

,NOMBRE_PASAJERO,BOLETOS_VEND,CLASE_SERVICIO,DESC_DESCUENTO,DIAS_ANTICIPACION,EMAIL,FECHA_CORRIDA,FECHA_OPERACION,HORAS_ANTICIPACION,PAGO_METODO,PORCENT_PROMO,TIPO_CORRIDA,TIPO_PASAJERO,TOTAL_BOLETOS,VENTA,VENTA_ANTICIPADA,VENTA_TOTAL,%_Tarifa Personalizada,Cluster,Delta_Q
0,PEDRO CHAVEZ SANDOVAL,1.0,DOS PISOS ETN,MENOR,0,LIZMIR8@OUTLOOK.COM,2025-10-24 00:00:00,2025-10-24 00:00:00,2.0,EFECTIVO,0.0,NORMAL,NI,1.0,977.583618,1,609.909973,2.5,0,1.958067
1,ALICIA ROLDAN GARCIA,1.0,DOS PISOS ETN,MENOR,0,alicia.roldan.garcia@ejemplo.com,2025-10-24 00:00:00,2025-10-24 00:00:00,1.0,EFECTIVO,0.0,NORMAL,NI,1.0,977.583618,1,609.909973,10.0,3,7.832267
2,GLORIA MIRANDA DURAN,1.0,DOS PISOS ETN,MENOR,0,gloria.miranda.duran@ejemplo.com,2025-10-24 00:00:00,2025-10-24 00:00:00,1.0,EFECTIVO,0.0,NORMAL,NI,1.0,977.583618,1,609.909973,10.0,3,7.832267
3,MARCELO MIRANDA,1.0,DOS PISOS ETN,ADULTO,0,marcelo.miranda@ejemplo.com,2025-10-24 00:00:00,2025-10-24 00:00:00,1.0,EFECTIVO,0.0,NORMAL,AD,1.0,977.583618,1,1219.829956,7.0,4,5.482587
4,IGNACIO MIRANDA,1.0,DOS PISOS ETN,ADULTO,0,ignacio.miranda@ejemplo.com,2025-10-24 00:00:00,2025-10-24 00:00:00,1.0,EFECTIVO,0.0,NORMAL,AD,1.0,977.583618,1,1219.829956,7.0,4,5.482587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,RAMON REBOLLEDO,1.0,DOS PISOS ETN,ADULTO,0,ramon.rebolledo@ejemplo.com,2025-11-12 00:00:00,2025-11-12 00:00:00,1.0,EFECTIVO,0.0,NORMAL,AD,1.0,977.583618,0,1219.829956,8.5,1,6.657427
2306,PAULINA LLAMAS CASILLAS,1.0,DOS PISOS ETN,PROMOCION ESPECIAL,0,paulina.llamas.casillas@ejemplo.com,2025-11-12 00:00:00,2025-11-12 00:00:00,13.0,EFECTIVO,5.0,NORMAL,AD,1.0,977.583618,0,1158.880005,0.0,5,0.000000
2307,ARTURO CHAVEZ,1.0,DOS PISOS ETN,ADULTO,0,arturo.chavez@ejemplo.com,2025-11-12 00:00:00,2025-11-12 00:00:00,1.0,EFECTIVO,0.0,NORMAL,AD,1.0,977.583618,0,1219.829956,8.5,1,6.657427
2308,MOISES PENHOS,1.0,DOS PISOS ETN,ADULTO,0,moises.penhos@ejemplo.com,2025-11-12 00:00:00,2025-11-12 00:00:00,1.0,EFECTIVO,0.0,NORMAL,AD,1.0,977.583618,0,1219.829956,8.5,1,6.657427
2309,ADRIANA ARMENTA RAMIREZ,1.0,DOS PISOS ETN,SENECTUD,0,adriana.armenta.ramirez@ejemplo.com,2025-11-12 00:00:00,2025-11-12 00:00:00,1.0,EFECTIVO,0.0,NORMAL,IN,1.0,977.583618,0,609.909973,5.0,2,3.916133

# <div align="left"><font size="5">📌Merge de las tarifas</font></div>

Para finalizar este pipeline, se combinan los dataframes obtenidos de la red neuronal del precio dinámico con el del algoritmo de clasificación del precio personalizado

In [15]:
df_combinado = pd.concat(
    [TodayDataPD.reset_index(drop=True), TodayDataTP.reset_index(drop=True)],
    axis=1
)
df_combinado = df_combinado.loc[:, ~df_combinado.columns.duplicated()]

In [16]:
TodayDataTP.columns, TodayDataPD.columns

(Index(['NOMBRE_PASAJERO', 'BOLETOS_VEND', 'CLASE_SERVICIO', 'DESC_DESCUENTO',
        'DIAS_ANTICIPACION', 'EMAIL', 'FECHA_CORRIDA', 'FECHA_OPERACION',
        'HORAS_ANTICIPACION', 'PAGO_METODO', 'PORCENT_PROMO', 'TIPO_CORRIDA',
        'TIPO_PASAJERO', 'TOTAL_BOLETOS', 'VENTA', 'VENTA_ANTICIPADA',
        'VENTA_TOTAL', '%_Tarifa Personalizada', 'Cluster', 'Delta_Q'],
       dtype='object'),
 Index(['NOMBRE_PASAJERO', 'BOLETOS_VEND', 'FECHA_CORRIDA',
        'HORA_SALIDA_CORRIDA', 'CLASE_SERVICIO', 'IVA_TARIFA_BASE_TRAMO',
        'PAX_SUBEN', 'TARIFA_BASE_TRAMO', 'FECHA_OPERACION', 'HORA_OPERACION',
        'VENTA', 'DISPONIBILIDAD_TRAMO', 'HORAS_ANTICIPACION', 'ORIGEN',
        'DESTINO', 'TIPO_CLIENTE', 'NUM_ASIENTO', 'CAPACIDAD_ASIENTOS_TRAMO',
        'TIPO_PASAJERO', 'TARIFA DINAMICA'],
       dtype='object'))

In [17]:
df_combinado.columns

Index(['NOMBRE_PASAJERO', 'BOLETOS_VEND', 'FECHA_CORRIDA',
       'HORA_SALIDA_CORRIDA', 'CLASE_SERVICIO', 'IVA_TARIFA_BASE_TRAMO',
       'PAX_SUBEN', 'TARIFA_BASE_TRAMO', 'FECHA_OPERACION', 'HORA_OPERACION',
       'VENTA', 'DISPONIBILIDAD_TRAMO', 'HORAS_ANTICIPACION', 'ORIGEN',
       'DESTINO', 'TIPO_CLIENTE', 'NUM_ASIENTO', 'CAPACIDAD_ASIENTOS_TRAMO',
       'TIPO_PASAJERO', 'TARIFA DINAMICA', 'DESC_DESCUENTO',
       'DIAS_ANTICIPACION', 'EMAIL', 'PAGO_METODO', 'PORCENT_PROMO',
       'TIPO_CORRIDA', 'TOTAL_BOLETOS', 'VENTA_ANTICIPADA', 'VENTA_TOTAL',
       '%_Tarifa Personalizada', 'Cluster', 'Delta_Q'],
      dtype='object')

In [18]:
df_combinado

,NOMBRE_PASAJERO,BOLETOS_VEND,FECHA_CORRIDA,HORA_SALIDA_CORRIDA,CLASE_SERVICIO,IVA_TARIFA_BASE_TRAMO,PAX_SUBEN,TARIFA_BASE_TRAMO,FECHA_OPERACION,HORA_OPERACION,...,EMAIL,PAGO_METODO,PORCENT_PROMO,TIPO_CORRIDA,TOTAL_BOLETOS,VENTA_ANTICIPADA,VENTA_TOTAL,%_Tarifa Personalizada,Cluster,Delta_Q
0,PEDRO CHAVEZ SANDOVAL,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 00:32:16,...,LIZMIR8@OUTLOOK.COM,EFECTIVO,0.0,NORMAL,1.0,1,609.909973,2.5,0,1.958067
1,ALICIA ROLDAN GARCIA,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 01:17:23,...,alicia.roldan.garcia@ejemplo.com,EFECTIVO,0.0,NORMAL,1.0,1,609.909973,10.0,3,7.832267
2,GLORIA MIRANDA DURAN,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 01:17:23,...,gloria.miranda.duran@ejemplo.com,EFECTIVO,0.0,NORMAL,1.0,1,609.909973,10.0,3,7.832267
3,MARCELO MIRANDA,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 01:17:23,...,marcelo.miranda@ejemplo.com,EFECTIVO,0.0,NORMAL,1.0,1,1219.829956,7.0,4,5.482587
4,IGNACIO MIRANDA,1.0,2025-10-24 00:00:00,1900-01-01 02:00:00,DOS PISOS ETN,186.206406,34,1163.790039,2025-10-24 00:00:00,1900-01-01 01:17:23,...,ignacio.miranda@ejemplo.com,EFECTIVO,0.0,NORMAL,1.0,1,1219.829956,7.0,4,5.482587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,RAMON REBOLLEDO,1.0,2025-11-12 00:00:00,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12 00:00:00,1900-01-01 10:11:31,...,ramon.rebolledo@ejemplo.com,EFECTIVO,0.0,NORMAL,1.0,0,1219.829956,8.5,1,6.657427
2306,PAULINA LLAMAS CASILLAS,1.0,2025-11-12 00:00:00,1900-01-01 23:59:00,DOS PISOS ETN,186.206406,9,1163.790039,2025-11-12 00:00:00,1900-01-01 10:16:35,...,paulina.llamas.casillas@ejemplo.com,EFECTIVO,5.0,NORMAL,1.0,0,1158.880005,0.0,5,0.000000
2307,ARTURO CHAVEZ,1.0,2025-11-12 00:00:00,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12 00:00:00,1900-01-01 10:45:16,...,arturo.chavez@ejemplo.com,EFECTIVO,0.0,NORMAL,1.0,0,1219.829956,8.5,1,6.657427
2308,MOISES PENHOS,1.0,2025-11-12 00:00:00,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12 00:00:00,1900-01-01 10:47:24,...,moises.penhos@ejemplo.com,EFECTIVO,0.0,NORMAL,1.0,0,1219.829956,8.5,1,6.657427
2309,ADRIANA ARMENTA RAMIREZ,1.0,2025-11-12 00:00:00,1900-01-01 11:00:00,DOS PISOS ETN,186.206406,16,1163.790039,2025-11-12 00:00:00,1900-01-01 10:48:10,...,adriana.armenta.ramirez@ejemplo.com,EFECTIVO,0.0,NORMAL,1.0,0,609.909973,5.0,2,3.916133

In [19]:
df_PD= df_combinado[['FECHA_OPERACION','NOMBRE_PASAJERO','NUM_ASIENTO','CAPACIDAD_ASIENTOS_TRAMO',
                     'HORA_SALIDA_CORRIDA', 'EMAIL','Cluster', 'TARIFA DINAMICA', '%_Tarifa Personalizada','TARIFA_BASE_TRAMO'
                     ,"Delta_Q",'VENTA_TOTAL','TIPO_PASAJERO','BOLETOS_VEND']]
df_PD ['Precio final con IVA']= df_PD['TARIFA DINAMICA']*(df_PD['%_Tarifa Personalizada']/100)+ df_PD['TARIFA DINAMICA']+df_PD['TARIFA DINAMICA']*0.16
df_PD ['Precio final con IVA']= np.round(df_PD ['Precio final con IVA'])

df_PD ['Precio final sin IVA']= df_PD['TARIFA DINAMICA']*(df_PD['%_Tarifa Personalizada']/100)+ df_PD['TARIFA DINAMICA']
df_PD ['Precio final sin IVA']= np.round(df_PD ['Precio final sin IVA'])

In [20]:
df_PD

,FECHA_OPERACION,NOMBRE_PASAJERO,NUM_ASIENTO,CAPACIDAD_ASIENTOS_TRAMO,HORA_SALIDA_CORRIDA,EMAIL,Cluster,TARIFA DINAMICA,%_Tarifa Personalizada,TARIFA_BASE_TRAMO,Delta_Q,VENTA_TOTAL,TIPO_PASAJERO,BOLETOS_VEND,Precio final con IVA,Precio final sin IVA
0,2025-10-24 00:00:00,PEDRO CHAVEZ SANDOVAL,10,36,1900-01-01 02:00:00,LIZMIR8@OUTLOOK.COM,0,1081.420166,2.5,1163.790039,1.958067,609.909973,NI,1.0,1281.0,1108.0
1,2025-10-24 00:00:00,ALICIA ROLDAN GARCIA,8,36,1900-01-01 02:00:00,alicia.roldan.garcia@ejemplo.com,3,1081.455322,10.0,1163.790039,7.832267,609.909973,NI,1.0,1363.0,1190.0
2,2025-10-24 00:00:00,GLORIA MIRANDA DURAN,9,36,1900-01-01 02:00:00,gloria.miranda.duran@ejemplo.com,3,1081.437378,10.0,1163.790039,7.832267,609.909973,NI,1.0,1363.0,1190.0
3,2025-10-24 00:00:00,MARCELO MIRANDA,11,36,1900-01-01 02:00:00,marcelo.miranda@ejemplo.com,4,1081.401489,7.0,1163.790039,5.482587,1219.829956,AD,1.0,1330.0,1157.0
4,2025-10-24 00:00:00,IGNACIO MIRANDA,12,36,1900-01-01 02:00:00,ignacio.miranda@ejemplo.com,4,1081.383423,7.0,1163.790039,5.482587,1219.829956,AD,1.0,1330.0,1157.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,2025-11-12 00:00:00,RAMON REBOLLEDO,36,36,1900-01-01 11:00:00,ramon.rebolledo@ejemplo.com,1,1080.785278,8.5,1163.790039,6.657427,1219.829956,AD,1.0,1346.0,1173.0
2306,2025-11-12 00:00:00,PAULINA LLAMAS CASILLAS,13,36,1900-01-01 23:59:00,paulina.llamas.casillas@ejemplo.com,5,1081.106201,0.0,1163.790039,0.000000,1158.880005,AD,1.0,1254.0,1081.0
2307,2025-11-12 00:00:00,ARTURO CHAVEZ,30,36,1900-01-01 11:00:00,arturo.chavez@ejemplo.com,1,1080.893188,8.5,1163.790039,6.657427,1219.829956,AD,1.0,1346.0,1173.0
2308,2025-11-12 00:00:00,MOISES PENHOS,24,36,1900-01-01 11:00:00,moises.penhos@ejemplo.com,1,1081.001343,8.5,1163.790039,6.657427,1219.829956,AD,1.0,1346.0,1173.0
2309,2025-11-12 00:00:00,ADRIANA ARMENTA RAMIREZ,18,36,1900-01-01 11:00:00,adriana.armenta.ramirez@ejemplo.com,2,1081.230835,5.0,1163.790039,3.916133,609.909973,IN,1.0,1308.0,1135.0

El siguiente dataframe muestra los precios dinámicos con el 15 porciento de IVA para cada uno de los usuarios del presente día según su clasificación obtenida con los algoritmos de aprendizaje.

In [21]:
acla_keys = ['PF', 'AD', 'ES', 'IN', 'MA', 'NI', 'PD', 'PE', 'XA', 'ZA', 'ZB', 'VC', 'PH', 'FA', 'OD', 'XP', 'IF', 'SC']
porcentaje_values = [25, 0, 50, 50, 25, 50, 25, 0, 5, 0, 10, 25, 6, 0, 50, 25, 0, 0]

# Crear el diccionario (Mapeo de código a porcentaje entero)
diccionario_acla_porcentaje = dict(zip(acla_keys, porcentaje_values))

# 1. Mapea el TIPO_PASAJERO al porcentaje entero (25, 50, 0, etc.)
# 2. Divide entre 100 para convertirlo al factor decimal (0.25, 0.50, 0.0)
df_PD['Descuento'] = df_PD['TIPO_PASAJERO'].map(diccionario_acla_porcentaje) / 100


df_PD['Precio a consumidor']= (1-df_PD['Descuento'])* df_PD['Precio final sin IVA']

In [22]:
df_PD

,FECHA_OPERACION,NOMBRE_PASAJERO,NUM_ASIENTO,CAPACIDAD_ASIENTOS_TRAMO,HORA_SALIDA_CORRIDA,EMAIL,Cluster,TARIFA DINAMICA,%_Tarifa Personalizada,TARIFA_BASE_TRAMO,Delta_Q,VENTA_TOTAL,TIPO_PASAJERO,BOLETOS_VEND,Precio final con IVA,Precio final sin IVA,Descuento,Precio a consumidor
0,2025-10-24 00:00:00,PEDRO CHAVEZ SANDOVAL,10,36,1900-01-01 02:00:00,LIZMIR8@OUTLOOK.COM,0,1081.420166,2.5,1163.790039,1.958067,609.909973,NI,1.0,1281.0,1108.0,0.5,554.0
1,2025-10-24 00:00:00,ALICIA ROLDAN GARCIA,8,36,1900-01-01 02:00:00,alicia.roldan.garcia@ejemplo.com,3,1081.455322,10.0,1163.790039,7.832267,609.909973,NI,1.0,1363.0,1190.0,0.5,595.0
2,2025-10-24 00:00:00,GLORIA MIRANDA DURAN,9,36,1900-01-01 02:00:00,gloria.miranda.duran@ejemplo.com,3,1081.437378,10.0,1163.790039,7.832267,609.909973,NI,1.0,1363.0,1190.0,0.5,595.0
3,2025-10-24 00:00:00,MARCELO MIRANDA,11,36,1900-01-01 02:00:00,marcelo.miranda@ejemplo.com,4,1081.401489,7.0,1163.790039,5.482587,1219.829956,AD,1.0,1330.0,1157.0,0.0,1157.0
4,2025-10-24 00:00:00,IGNACIO MIRANDA,12,36,1900-01-01 02:00:00,ignacio.miranda@ejemplo.com,4,1081.383423,7.0,1163.790039,5.482587,1219.829956,AD,1.0,1330.0,1157.0,0.0,1157.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,2025-11-12 00:00:00,RAMON REBOLLEDO,36,36,1900-01-01 11:00:00,ramon.rebolledo@ejemplo.com,1,1080.785278,8.5,1163.790039,6.657427,1219.829956,AD,1.0,1346.0,1173.0,0.0,1173.0
2306,2025-11-12 00:00:00,PAULINA LLAMAS CASILLAS,13,36,1900-01-01 23:59:00,paulina.llamas.casillas@ejemplo.com,5,1081.106201,0.0,1163.790039,0.000000,1158.880005,AD,1.0,1254.0,1081.0,0.0,1081.0
2307,2025-11-12 00:00:00,ARTURO CHAVEZ,30,36,1900-01-01 11:00:00,arturo.chavez@ejemplo.com,1,1080.893188,8.5,1163.790039,6.657427,1219.829956,AD,1.0,1346.0,1173.0,0.0,1173.0
2308,2025-11-12 00:00:00,MOISES PENHOS,24,36,1900-01-01 11:00:00,moises.penhos@ejemplo.com,1,1081.001343,8.5,1163.790039,6.657427,1219.829956,AD,1.0,1346.0,1173.0,0.0,1173.0
2309,2025-11-12 00:00:00,ADRIANA ARMENTA RAMIREZ,18,36,1900-01-01 11:00:00,adriana.armenta.ramirez@ejemplo.com,2,1081.230835,5.0,1163.790039,3.916133,609.909973,IN,1.0,1308.0,1135.0,0.5,567.5

In [23]:
# solo para el final del dia
df_PD.to_csv('datos_dinamicos.csv', index=False)

In [24]:
ruta_principal = os.getcwd()
config_path = os.path.join(ruta_principal, "Files", 'datos_dinamicos.parquet')
df_PD.to_parquet(config_path, index=False)
config_path = os.path.join(ruta_principal, "Files", 'datos_dinamicos.csv')
df_PD.to_csv(config_path, index=False)

In [25]:
df_final = df_PD.groupby('FECHA_OPERACION')[['TARIFA DINAMICA', 'Precio final con IVA', 'Precio final sin IVA']].sum()
#df_final.to_csv('TarifaPrecios.csv')